Fix call stack size exceeded when set atom value with object that has circular reference (#153)
Summary:
## Background

fix https://github.com/facebookexperimental/Recoil/issues/54

Set atom value with an object that has circular reference inside will cause an error

```
RangeError: Maximum call stack size exceeded
```

## What's changed

- In `deepFreezeValue`  Check if a property is already frozen
Pull Request resolved: https://github.com/facebookexperimental/Recoil/pull/153

Reviewed By: mondaychen

Differential Revision: D21712576

Pulled By: drarmstr

fbshipit-source-id: f44e9ee303e2bbf566cc18f09f64f2b0ade14123